export { ArrowIosForwardOutline } from '@styled-icons/evaicons-outline/ArrowIosForwardOutline'
export { Play } from '@styled-icons/boxicons-regular/Play'
export { Heart } from '@styled-icons/boxicons-regular/Heart'
export { Heart as SolidHeart } from '@styled-icons/boxicons-solid/Heart'
export { ArrowGoBack } from '@styled-icons/remix-fill/ArrowGoBack'
export { AddToQueue } from '@styled-icons/boxicons-solid/AddToQueue'
